### ISSUE TITLE
Peanuts transcript index

### ISSUE THREAD

**Issue by uZ7777** [anjum-ahmed/peanuts-search#8]
Hi, Anjum
Could you modify the peanuts transcript index under wiki to show that the years 1955, 1959 and 1961 are in progress? Thanks

**Comment by alan850627** [comment]
Haha. Again, those 'file statuses' are really comments when we commit and push to git. It helps us track what we changed. You can see the "in-progress" tags in the files itself, so really no point in putting it in the comment. That's my personal opinion. Anjum, do whatever you want.

**Comment by uZ7777** [comment]
I mean here: https://github.com/anjum-ahmed/peanuts-search/wiki/Peanuts-transcripts-index

Just for the sake of making it easy for people to see our progress.

alan850627 <notifications@github.com> wrote:


Haha. Again, those 'file statuses' are really comments when we commit and push to git. It helps us track what we changed. You can see the "in-progress" tags in the files itself, so really no point in putting it in the comment. That's my personal opinion. Anjum, do whatever you want.

-

**Comment by anjum-ahmed** [comment]
You should be able to edit it, uZ7777.
